CREATE DATABASE prac2;

USE prac2;


CREATE TABLE Users (
    email VARCHAR(100) PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    accountId INT UNIQUE NOT NULL
);

CREATE TABLE News (
    newsId INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(50) NOT NULL,
    body TEXT,
    dateTime DATETIME NOT NULL
);